// Centralized route paths for use in tests and app
// ALL test files MUST use these paths - NO hardcoded URLs allowed
export const paths = {
  home: '/',
  shop: '/shop',
  pixelParla: '/shop/pixelparla',
  resin: '/shop/resin',
  junior: '/shop/junior',
  cart: '/cart',
  checkout: '/checkout',
  about: '/about',
  // Helper for constructing product detail paths
  productDetail: (category: string, productId: string) => `/shop/${category}/${productId}`,
  // Helper for constructing category paths
  category: (category: string) => `/shop/${category}`,
};

export const texts = {
  site: {
    name: "Pixelverk",
    tagline: "Som lagom fast tvärtom",
    description: "Handgjorda smycken med lekfull nostalgi, havskänsla och stilla silver. Skapade i liten skala – ibland färgglatt, ibland avskalat.",
  },
  currency: {
    suffix: " kr",
  },
  forms: {
    name: "Namn",
    email: "E-post",
    address: "Adress",
    namePlaceholder: "För- och efternamn",
    emailPlaceholder: "din@epost.se",
    addressPlaceholder: "Gatuadress",
  },
  nav: {
    home: "Hem",
    shop: "Shop",
    about: "Om Pixelverk",
    cart: "Kundvagn",
    checkout: "Kassa",
    junior: "Pixelverk Junior",
    admin: "Admin",
    toggleMenu: "Växla meny",
    showAll: "Visa alla",
  },
  shop: {
    title: "Shop",
    sortBy: "Sortera efter:",
    sortOptions: {
      newest: "Nyast först",
      priceLow: "Lägsta pris",
      priceHigh: "Högsta pris",
      name: "Namn A-Ö",
    },
    categories: {
      pixelparla: "Pixel & Pärla",
      resin: "Resin & Natur",
      junior: "Pixelverk Junior",
    },
    noProducts: "Inga produkter hittades",
  },
  product: {
    notFound: "Produkten hittades inte",
    addToCart: "Lägg i kundvagn",
    price: "Pris",
    description: "Beskrivning",
    backToShop: "Tillbaka till shoppen",
    backArrow: "←",
    prevImage: "Föregående bild",
    nextImage: "Nästa bild",
    prevArrow: "←",
    nextArrow: "→",
    selectImage: "Välj bild",
    inStock: "I lager: ",
    outOfStock: "Slut i lager",
    inCart: "I din varukorg: ",
    removeFromCart: "Ta bort från kundvagn",
    maxStockReached: "Max antal i lager",
  },
  cart: {
    title: "Din kundvagn",
    empty: "Din kundvagn är tom",
    continueShopping: "Fortsätt handla",
    goToCheckout: "Gå till kassan",
    total: "Totalt",
    quantity: "Antal",
    remove: "Ta bort",
    itemsInCart: "produkter i kundvagnen",
    decreaseQuantity: "Minska antal",
    increaseQuantity: "Öka antal",
  },
  checkout: {
    title: "Kassa",
    payment: "Betalning",
    mockPayment: "Detta är en demo-checkout",
    completeOrder: "Slutför köp",
    thankYou: "Tack för din beställning!",
    orderSummary: "Ordersammanfattning",
    orderNumber: "Ordernummer",
    backToShop: "Tillbaka till shoppen",
    confirmationSent: "En bekräftelse har skickats till din e-post.",
  },
  buttons: {
    addToCart: "Lägg i kundvagn",
    shopNow: "Shoppa nu",
    learnMore: "Läs mer",
    contact: "Kontakta oss",
    submit: "Skicka",
  },
    admin: {
      title: "Hantera produkter",
      subtitle: "Lägg till nya produkter eller fler bilder direkt i filstrukturen (public/products).",
      locked: "Sidan är låst. Ange lösenordet för att komma åt administrationsverktyget.",
      missingPassword: "ADMIN_PASSWORD saknas i miljövariablerna. Lägg till den i din utvecklingsmiljö.",
      fields: {
        category: "Kategori",
        productId: "Produkt-ID / mappnamn",
        name: "Produktnamn",
        price: "Pris",
        stock: "Lagersaldo",
        description: "Beskrivning",
        images: "Bilder",
        password: "Lösenord",
      },
      placeholders: {
        name: "Exempel: Pixelhjärta örhänge",
        description: "Beskriv färg, material, storlek och andra detaljer.",
      },
    create: {
      heading: "Lägg till ny produkt",
      description: "Formuläret skapar en ny mapp med info.json och sparar bilderna i en images-mapp.",
      folderHint: "Mappnamn använder bara små bokstäver, siffror och bindestreck.",
      imageHint: "Bilder döps automatiskt i ordning (01.jpg, 02.jpg ...).",
      submit: "Spara produkt",
      submitting: "Sparar...",
        },
        images: {
          heading: "Lägg till fler bilder",
          description: "Välj en befintlig produkt och ladda upp extra bilder. De läggs till efter befintliga filer.",
          productHint: "Du kan välja från listan eller skriva mappnamnet manuellt.",
          imageHint: "Bilderna numreras automatiskt efter senaste fil.",
          submit: "Lägg till bilder",
          submitting: "Laddar upp...",
          currentFolders: "Befintliga produktmappar",
          noProducts: "Inga produkter i den här kategorin ännu.",
        },
        auth: {
          heading: "Logga in",
          submit: "Öppna admin",
          submitting: "Verifierar...",
          logout: "Logga ut",
          error: "Fel lösenord, försök igen.",
          success: "Inloggad! Laddar admin...",
        },
      },
  home: {
    hero: {
      title: "Pixelverk",
      tagline: "När lagom inte räcker till",
      description: "Handgjorda smycken med lekfull nostalgi och naturinspiration. Här hittar du retro-pärlplatte-örhängen och resin-smycken inspirerade av hav, blad och blomformer.",
    },
    cta: {
      shop: "Shoppa nu",
      about: "Om Pixelverk",
    },
    categories: {
      pixelparlaDesc: "Retro-pärlplatte med 80/90-tals nostalgi",
      resinDesc: "Hav, blad och blomformer i resin",
      juniorDesc: "Färgglada pärlfigurer för små händer",
    },
    news: {
      title: "Nyheter & Kampanjer",
      description: "Håll utkik här för kommande kampanjer och nya produkter!",
      link: "Se alla produkter →",
    },
  },
  about: {
    title: "Om Pixelverk",
    intro: "Pixelverk är mitt sätt att skapa utan att välja en enda stil. Inspirerad av 80- och 90-talets färger, havets lugn och klassiska silverformer gör jag smycken som får vara lite för mycket – eller precis lagom, fast tvärtom.",
    details: "Allt skapas för hand, i liten skala, med tid och omsorg.",
  },
  junior: {
    title: "Pixelverk Junior",
    description: "Här hittar du små pärlfigurer inspirerade av Tetris och andra färgglada minnen. Skapade med fantasi och glädje.",
  },
  errors: {
    loadError: "Ett fel uppstod vid laddning",
    categoryNotFound: "Kategorin hittades inte",
    productNotFound: "Produkten hittades inte",
  },
  footer: {
    contact: "Kontakt",
    openingHours: "Öppettider:",
    weekdays: "Vardagar",
    weekends: "Helger",
    quickLinks: "Snabblänkar",
    social: "Följ oss",
    faq: "Vanliga frågor",
    rightsReserved: "Alla rättigheter förbehållna.",
  },
};
